### ISSUE TITLE
moqup_web_todos_main

### ISSUE THREAD

**Issue by hscsf** [CloudyDirk/cloud57#11]
![moqup_web_todos_main](https://cloud.githubusercontent.com/assets/15434603/11015766/d0bd8d20-856b-11e5-8a46-b8b5fff4b1d6.png)

**Comment by hscsf** [comment]
Der Screenshot wurde als Issue dem Repository hinzugefügt. Damit kann er ganz leicht in den MD-Files referenziert werden. Nicht so schön ist, dass der Screenshot (weil er ein Issue ist) auch in Waffle auftaucht. Mmmm?!

**Comment by CloudyDirk** [comment]
Hi, 

was spricht dagegen den Screenshot als Datei in dem Architektur Ordner hinzuzufügen? 

Mit Outlook für Android gesendet

On Sat, Nov 7, 2015 at 7:47 AM -0800, "hscsf" notifications@github.com wrote:

Der Screenshot wurde als Issue dem Repository hinzugefügt. Damit kann er ganz leicht in den MD-Files referenziert werden. Nicht so schön ist, dass der Screenshot (weil er ein Issue ist) auch in Waffle auftaucht. Mmmm?!

**Comment by hscsf** [comment]
Da spricht natürlich nichts dagegen :smile:

Wie gesagt, ich hatte mit dem Web-Frontend von GitHub gespielt und keine direkte Upload-Funktion gefunden. Und mit dem Issue-Trick hat das dann irgendwie gut funktioniert (zumindest erstmal).

**Comment by hscsf** [comment]
Ich schließe dieses Issue dann mal.
